//! `counter` mini-app — now a **WASM component**.
//!
//! Compared with the old core-module version there is NO hand-written
//! `(ptr, len)` ABI and NO `guest_alloc`: the bindings below are generated by
//! `wit-bindgen` from the shared `wit/` package, and the Component Model's
//! canonical ABI moves the strings/bools across the boundary. The app logic is
//! identical — the count lives here, inside the guest; the host only renders the
//! labels/buttons this app describes and routes clicks back.

use std::sync::atomic::{AtomicI32, Ordering};

wit_bindgen::generate!({
    world: "mini-app",
    path: "../../wit",
});

// The generated host imports — our capability set — as ordinary functions.
use nimadir::shell::host_api::{log, now_millis, ui_button, ui_label};

/// App state, owned by the guest.
static COUNT: AtomicI32 = AtomicI32::new(0);

struct Counter;

impl Guest for Counter {
    /// One-time setup — also exercises a host capability (`now-millis`).
    fn init() {
        let now = now_millis();
        log(&format!("counter mini-app: init at host-time {now}"));
    }

    /// Called once per frame. Describe the UI; react to clicks.
    fn update() {
        let count = COUNT.load(Ordering::Relaxed);
        ui_label(&format!("Count: {count}"));

        // Button index 0.
        if ui_button("Increment") {
            COUNT.fetch_add(1, Ordering::Relaxed);
        }
        // Button index 1.
        if ui_button("Reset") {
            COUNT.store(0, Ordering::Relaxed);
        }
    }
}

export!(Counter);
