// counter-cs — the first C# mini-app, compiled to a WASM *component* by
// componentize-dotnet (NativeAOT-LLVM).
//
// It targets the SAME wit/world.wit as the Rust mini-apps, so the host loads and
// runs it with ZERO host changes. That is the whole point of the Component Model
// migration: the interface is the contract, not the language. The count lives
// here in the guest, exactly like the Rust `counter`; the host only renders.
//
// Bindings are generated by wit-bindgen at build time:
//   - exports: implement `MiniAppWorldExportsImpl` (the generated glue calls it)
//   - imports: call the host via `IHostApiImports` (Log/UiLabel/UiButton/NowMillis)

using MiniAppWorld;
using static MiniAppWorld.wit.Imports.nimadir.shell.v0_1_0.IHostApiImports;

/// Implements the world's exports. The generated `[UnmanagedCallersOnly]` glue
/// (init/update wasm exports) forwards to these static methods.
public class MiniAppWorldExportsImpl : IMiniAppWorldExports
{
    /// App state, owned by the guest.
    private static int _count;

    /// One-time setup — also exercises a host capability (`now-millis`).
    public static void Init()
    {
        long now = NowMillis();
        Log($"counter-cs mini-app: init at host-time {now}");
    }

    /// Called once per frame. Describe the UI; react to clicks.
    public static void Update()
    {
        UiLabel($"Count (C#): {_count}");

        // Button index 0.
        if (UiButton("Increment"))
        {
            _count++;
        }
        // Button index 1.
        if (UiButton("Reset"))
        {
            _count = 0;
        }
    }
}
